name: "tfsuit"
description: "Fast Terraform naming linter & fixer"
inputs:
  path:
    description: "Directory to scan"
    default: "."
  config:
    description: "Config file (HCL/JSON)"
    default: "tfsuit.hcl"
  format:
    description: "pretty | json | sarif"
    default: "pretty"
  fail:
    description: "Fail the job if violations found"
    default: "false"
runs:
  using: "docker"
  image: "docker://ghcr.io/josdagaro/tfsuit:v${{ github.action_ref }}"
  args:
    - scan
    - ${{ inputs.path }}
    - --config
    - ${{ inputs.config }}
    - --format
    - ${{ inputs.format }}
    - ${{ inputs.fail == 'true' && '--fail' || '' }}
branding:
  icon: "check-square"
  color: "purple"
