# action/action.yml  (irá en la carpeta action/ del mismo repo)
name: "tfsuit"
description: "Terraform naming linter & fixer (Go, super-fast)"
author: "José David García Rodríguez"

inputs:
  path:
    description: "Ruta del código Terraform a analizar"
    required: false
    default: "."
  config:
    description: "Archivo HCL/JSON de reglas (ej. tfsuit.hcl)"
    required: false
    default: "tfsuit.hcl"
  format:
    description: "pretty | json | sarif"
    required: false
    default: "pretty"
  fail:
    description: "true = action falla si hay violaciones"
    required: false
    default: "false"
  debug:
    description: "true para salida detallada"
    required: false
    default: "false"

outputs:
  findings:
    description: "Listado JSON de violaciones (si format=json)"

branding:
  icon: "box"
  color: "green"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.path }}
    - --config=${{ inputs.config }}
    - --format=${{ inputs.format }}
    - ${{ inputs.fail == 'true' && '--fail' || '' }}
