name: "tfsuit"
description: "Terraform customizable tool for defining your standards, styles, and naming conventions"
inputs:
  dir:
    description: "Whether the project is a module or a digital product (available values to pass are: | proj | mod |)"
    required: true
  config_json_path:
    description: "The TF project directory will be analyzed"
    required: true
  fail_on_not_compliant:
    description: "Whether to launch an exit 1 when it detects there are some rules that weren't accomplished"
    required: false
    default: "false"
  docs_link:
    description: "Related documentation link to show when tfsuit fails because not compliant rules"
    required: false
    default: ""
  github_actions:
    description: "Whether to set GitHub Actions outputs or not"
    required: false
    default: "true"
outputs:
  compliant_vars:
    description: "A JSON list of compliant vars"
  not_complaint_vars:
    description: "A JSON list of not compliant vars"
  compliant_outputs:
    description: "A JSON list of compliant outputs"
  not_compliant_outputs:
    description: "A JSON list of not compliant outputs"
  compliant_modules:
    description: "A JSON list of compliant modules"
  not_compliant_modules:
    description: "A JSON list of not compliant modules"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dir }}
    - ${{ inputs.config_json_path }}
    - ${{ inputs.fail_on_not_compliant }}
    - ${{ inputs.docs_link }}
    - ${{ inputs.github_actions }}
branding:
  icon: "box"
  color: "gray-dark"
