name: "Tests"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Install gsht
        run: |
          wget https://github.com/NekoOs/gsht.sh/releases/download/v0.1.0/gsht
          sudo cp gsht /usr/local/bin/gsht
          sudo chmod a+x /usr/local/bin/gsht
      - name: Install pcregrep
        run: sudo apt-get update -y && sudo apt-get install -y pcregrep
      - name: Transpile
        run: |
          gsht --input src/tfsuit.sh --output tfsuit
          sudo cp tfsuit /usr/local/bin/tfsuit
          sudo chmod a+x /usr/local/bin/tfsuit
      - name: Test
        run: tfsuit -c=tfsuit.example.json -d=tests
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "."
          ignore_paths: "src tests"
          severity: "warning" # options: error, warning, info, style
          additional_files: "tfsuit"
          format: tty

  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@v1.2.5
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PATH: CHANGELOG.md
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
    - name: See CHANGELOG.md
      run: |
        echo CHANGELOG.md
        git status
