name: Update Major Release Tag

on:
  release:
    types: [created]

jobs:
  move-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update Major Version
      id: major-version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        MAJOR=${VERSION%%.*}
        git tag -fa "$MAJOR" -m "Update major version tag $MAJOR"
        git push origin "$MAJOR" --force
        echo "version=v$MAJOR" >> "$GITHUB_OUTPUT"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Or Update Release
      id: gh-release
      uses: joutvhu/create-release@v1
      with:
        tag_name: ${{ steps.major-version.outputs.version }}
        name: Release ${{ steps.major-version.outputs.version }}
        draft: false
        prerelease: false
        on_release_exists: "update"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
